import json
import os
import random
import string

from datetime import datetime
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Image,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle(
    "TitleStyle",
    parent=styles["Heading1"],
    fontName="Helvetica-Bold",
    fontSize=24,
    textColor=colors.HexColor("#0B3D91"),
    alignment=TA_CENTER,
    spaceAfter=15,
)

SECTION_STYLE = ParagraphStyle(
    "SectionStyle",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=16,
    textColor=colors.HexColor("#0B3D91"),
    spaceBefore=12,
    spaceAfter=8,
)

BODY_STYLE = ParagraphStyle(
    "BodyStyle",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=10,
    leading=15,
)

FOOTER_STYLE = ParagraphStyle(
    "FooterStyle",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=9,
    alignment=TA_CENTER,
    textColor=colors.grey,
)

NAVY = colors.HexColor("#0B3D91")

GREEN = colors.HexColor("#16A34A")

RED = colors.HexColor("#DC2626")

PURPLE = colors.HexColor("#6B21A8")

ORANGE = colors.HexColor("#EA580C")

TEAL = colors.HexColor("#0F766E")

LIGHT = colors.HexColor("#F3F4F6")

WHITE = colors.white

# -----------------------------------
# Header Information
# -----------------------------------

def build_header(result):
    story = []

    # Divider Line
    divider = Table(
        [[""]],
        colWidths=[6.8*inch]
    )

    divider.setStyle(TableStyle([
        ("LINEBELOW", (0,0), (-1,-1), 1.2, NAVY),

        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))

    story.append(divider)

    # Logo
    logo_path = "static/images/logo.jpeg"

    if os.path.exists(logo_path):
        logo = Image(logo_path, width=0.8*inch, height=0.8*inch)
    else:
        logo = Paragraph("<b>PhishGuard</b>", BODY_STYLE)

    # Generated By
    generated_by = "PhishGuard v1.0 - Phishing Detection System"

    # Date & Time
    generated_time = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    # Report ID
    report_id = (
        "PHISH-"
        + datetime.now().strftime("%y%m%d")
        + "-"
        + "".join(random.choices(string.ascii_uppercase + string.digits, k=4))
    )

    # Information beside logo
    info = Paragraph(
        f"""
        <font size='18'><b>PHISHGUARD SECURITY REPORT</b></font><br/><br/>

        <b>Generated By :</b> {generated_by}<br/>
        <b>Generated On :</b> {generated_time}<br/>
        <b>Report ID :</b> {report_id}<br/>
        <b>Scanned URL :</b> {result['url']}
        """,
        BODY_STYLE
    )

    # Header Table
    header_table = Table(
        [[logo, info]], colWidths=[1.0*inch, 5.8*inch]
    )

    header_table.setStyle(TableStyle([

        ("VALIGN", (0,0), (-1,-1), "TOP"),

        ("LEFTPADDING", (0,0), (-1,-1), 0),

        ("RIGHTPADDING", (0,0), (-1,-1), 0),

        ("BOTTOMPADDING", (0,0), (-1,-1), 6)

    ]))

    story.append(header_table)

    story.append(Spacer(1,8))

    # Divider Line
    divider = Table(
        [[""]],
        colWidths=[6.8*inch]
    )

    divider.setStyle(TableStyle([
        ("LINEBELOW", (0,0), (-1,-1), 1.2, NAVY),

        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))

    story.append(divider)

    story.append(Spacer(1, 15))

    return story

    story.extend(build_header(result))

# -----------------------------
# RISK SUMMARY BANNER
# -----------------------------

def build_risk_summary(result):
    story = []

    risk = result["result"]["risk"]
    score = result["result"]["score"]

    # Choose banner color based on risk
    if risk == "SAFE":
        primary = colors.HexColor("#16A34A")
        light = colors.HexColor("#F4FBF6")
        verdict = f"""
        This URL appears to be 
        <font color='{primary}'><b>SAFE</b></font>.<br/> 
        No significant phishing or malicious indicators were detected.
        """

    elif risk == "SUSPICIOUS":
        primary = colors.HexColor("#F59E0B")
        light = colors.HexColor("#FFF8EB")
        verdict = f"""This URL appears to be 
        <font color='{primary}'><b>SUSPICIOUS</b></font>.<br/> 
        Some suspicious indicators were detected.
        """

    else:
        primary = colors.HexColor("#DC2626")
        light = colors.HexColor("#FEF2F2")
        verdict = f"""This URL appears to be 
        <font color='{primary}'><b>DANGEROUS</b></font>.<br/> 
        There is a high probability of phishing.
        """

    banner = Table(
        [[
            Paragraph(
                f"""
                <font color='black'>
                <b>RISK LEVEL</b><br/>
                <br/>
                <font color='{primary}' size='26'>
                <b>{risk}</b>
                </font>
                </font>
                """,
                BODY_STYLE
            ),

            Paragraph(
                f"""
                <font color='black'>
                <b>RISK SCORE</b><br/>
                <br/>
                <font color='{primary}' size='26'>
                <b>{score}/100</b>
                </font>
                </font>
                """,
                BODY_STYLE
            ),

            Paragraph(
                f"""
                <font color='black'>
                {verdict}
                </font>
                """,
                BODY_STYLE
            )
        ]],
        colWidths=[2.1*inch, 2.0*inch, 3.2*inch]
    )

    banner.setStyle(TableStyle([

        # White background
        ("BACKGROUND",(0,0),(-1,-1),light),

        # Light green border around the card
        ("BOX",(0,0),(-1,-1),1,primary),

        # Vertical separators
        ("LINEAFTER",(0,0),(0,-1),0.5,primary),
        ("LINEAFTER",(1,0),(1,-1),0.5,primary),
        ("LINEAFTER",(2,0),(2,-1),0.5,primary),

        ("TOPPADDING",(0,0),(-1,-1),12),
        ("BOTTOMPADDING",(0,0),(-1,-1),6),

        ("LEFTPADDING",(0,0),(-1,-1),12),
        ("RIGHTPADDING",(0,0),(-1,-1),12),

        ("VALIGN",(0,0),(-1,-1),"MIDDLE"),

        ("ALIGN",(3,0),(3,0),"LEFT"),

    ]))

    story.append(banner)

    # Divider Line
    divider = Table(
        [[""]],
        colWidths=[6.8*inch]
    )

    divider.setStyle(TableStyle([
        ("LINEBELOW", (0,0), (-1,-1), 1.2, NAVY),

        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))

    story.append(divider)

    story.append(Spacer(1, 4))

    return story

# -----------------------------
# Dashboard
# -----------------------------
def build_dashboard(result):
    story = []

    url_title = Paragraph(
        "<b>1. URL INFORMATION</b>",
        SECTION_STYLE
    )
    url_table = build_url_information(result)

    ssl_section = build_ssl_information(result)
    vt_section = build_virustotal_information(result)
    detection_summary_section = build_detection_summary(result)
    reasons_section = build_detection_reasons(result)

    # URL Information (Full Width)
    story.append(url_title)
    story.append(Spacer(1, 6))
    story.append(url_table)
    story.append(Spacer(1, 12))

    # SSL 
    story.append(
        Paragraph("<b>2. SSL CERTIFICATE</b>", SECTION_STYLE)
    )
    story.append(Spacer(1, 6))
    story.append(ssl_section)
    story.append(Spacer(1, 12))

    # VirusTotal
    story.append(
        Paragraph("<b>3. VIRUSTOTAL ANALYSIS</b>", SECTION_STYLE)
    )
    story.append(Spacer(1, 6))
    story.append(vt_section)
    story.append(Spacer(1, 12))

    # Detection Summary 
    story.append(
        Paragraph("<b>4. DETECTION SUMMARY</b>", SECTION_STYLE)
    )
    story.append(Spacer(1, 6))
    story.append(detection_summary_section)
    story.append(Spacer(1, 12))

    # Security Findings
    story.append(
        Paragraph("<b>5. SECURITY FINDINGS</b>", SECTION_STYLE)
    )
    story.append(Spacer(1, 6))
    story.append(reasons_section)
    story.append(Spacer(1, 12))

    return story

def build_url_information(result):

    url_data = [
        ["Parameter", "Details"],

        ["Protocol", result["basic_info"]["scheme"].upper()],

        ["Domain", result["basic_info"]["domain"]],

        ["Path", result["basic_info"]["path"] if result["basic_info"]["path"] else "-"],

        ["DNS Status", result["checks"]["dns_status"]],

        ["Domain Age",
        f"{result['checks']['domain_age']} days"],

        ["URL Length",
        str(result["checks"]["url_length"])],

        ["HTTPS",
        "Enabled" if result["checks"]["https"] else "Disabled"],

        ["IP Address",
        "Yes" if result["checks"]["ip_address"] else "No"]

    ]

    url_table = Table(
        url_data,
        colWidths=[2.3*inch,4.4*inch]
    )

    url_table.setStyle(TableStyle([
        # Parameter row
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#E8EEF8")),
        ("TEXTCOLOR",(0,0),(-1,0),NAVY),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        # Remaining rows
        ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#D1D5DB")),
        ("BACKGROUND",(0,1),(-1,-1),colors.white),
        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),
        ("LEFTPADDING",(0,0),(-1,-1),8),
    ]))

    # DNS Status
    dns_row = 4

    if result["checks"]["dns_status"] == "Valid":
        url_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,dns_row),(1,dns_row),colors.HexColor("#16A34A")),
            ("FONTNAME",(1,dns_row),(1,dns_row),"Helvetica-Bold"),
        ]))
    else:
        url_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,dns_row),(1,dns_row),colors.HexColor("#DC2626")),
            ("FONTNAME",(1,dns_row),(1,dns_row),"Helvetica-Bold"),
        ]))

    # HTTPS
    https_row = 7

    if result["checks"]["https"]:
        url_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,https_row),(1,https_row),colors.HexColor("#16A34A")),
            ("FONTNAME",(1,https_row),(1,https_row),"Helvetica-Bold"),
        ]))
    else:
        url_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,https_row),(1,https_row),colors.HexColor("#DC2626")),
            ("FONTNAME",(1,https_row),(1,https_row),"Helvetica-Bold"),
        ]))

    return url_table

# ---------------------------
# SSL
# ---------------------------

def build_ssl_information(result):

    ssl_data = [
        ["Parameter","Details"],

        ["Status", result["ssl"]["status"]],

        ["Issuer", result["ssl"]["issuer"]],

        ["Expiry Date", result["ssl"]["expiry"]],

        ["Days Remaining", str(result["ssl"]["days_left"])]

    ]

    ssl_table = Table(
        ssl_data,
        colWidths=[2.3*inch,4.4*inch]
    )

    ssl_table.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#E8F7EA")),
        ("TEXTCOLOR",(0,0),(-1,0),GREEN),
        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("BACKGROUND",(0,1),(-1,-1),WHITE),
        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),
        ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#D1D5DB")),
    ]))

    if result["ssl"]["status"] == "Valid":
        ssl_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,1),(1,1),colors.HexColor("#16A34A")),
            ("FONTNAME",(1,1),(1,1),"Helvetica-Bold"),
        ]))

    else:
        ssl_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,1),(1,1),colors.HexColor("#DC2626")),
            ("FONTNAME",(1,1),(1,1),"Helvetica-Bold"),
        ]))

    return ssl_table

# -------------------------------
# DETECTION SUMMARY
# -------------------------------
    
def build_detection_summary(result):

    summary_data = [

        ["Parameter", "Value"],

        ["Risk Level", result["result"]["risk"]],

        ["Risk Score", f"{result['result']['score']} / 100"],

        ["HTTPS", "Enabled" if result["checks"]["https"] else "Disabled"],

        ["DNS", result["checks"]["dns_status"]],

        ["SSL", result["ssl"]["status"]],

    ]

    table = Table(summary_data, colWidths=[2.3*inch,4.4*inch])

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#E8EEF8")),

        ("TEXTCOLOR",(0,0),(-1,0),PURPLE),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#D1D5DB")),

        ("BACKGROUND",(0,1),(-1,-1),WHITE),

        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),

        ("BOTTOMPADDING",(0,0),(-1,0),4),

        ("TOPPADDING",(0,0),(-1,0),4),

    ]))

    return table

# ---------------------------
# VirusTotal
# ---------------------------

def build_virustotal_information(result):

    vt_data = [

        ["Parameter", "Value"],

        ["Status", result["virustotal"]["status"]],

        ["Harmless", str(result["virustotal"]["harmless"])],

        ["Malicious", str(result["virustotal"]["malicious"])],

        ["Suspicious", str(result["virustotal"]["suspicious"])]

    ]

    vt_table = Table(
        vt_data,
        colWidths=[2.3*inch,4.4*inch]
    )

    vt_table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#E6F7F7")),

        ("TEXTCOLOR",(0,0),(-1,0),colors.HexColor("#0F766E")),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#D1D5DB")),

        ("BACKGROUND",(0,1),(-1,-1),WHITE),

        ("FONTNAME",(0,1),(0,-1),"Helvetica-Bold"),

        ("BOTTOMPADDING",(0,0),(-1,0),8),

        ("TOPPADDING",(0,0),(-1,0),8),

    ]))

    # Status colour
    if result["virustotal"]["status"] == "Available":
        vt_table.setStyle(TableStyle([
            ("TEXTCOLOR",(1,1),(1,1),GREEN),
            ("FONTNAME",(1,1),(1,1),"Helvetica-Bold"),
        ]))

    # Harmless
    vt_table.setStyle(TableStyle([
        ("TEXTCOLOR",(1,2),(1,2),GREEN),
        ("FONTNAME",(1,2),(1,2),"Helvetica-Bold"),
    ]))

    # Malicious
    vt_table.setStyle(TableStyle([
        ("TEXTCOLOR",(1,3),(1,3),RED),
        ("FONTNAME",(1,3),(1,3),"Helvetica-Bold"),
    ]))

    # Suspicious
    vt_table.setStyle(TableStyle([
        ("TEXTCOLOR",(1,4),(1,4),ORANGE),
        ("FONTNAME",(1,4),(1,4),"Helvetica-Bold"),
    ]))

    return vt_table

# ----------------------------
# DETECTION REASONS
# ----------------------------

def build_detection_reasons(result):

    findings = []

    # HTTPS
    if result["checks"]["https"]:
        findings.append(("GOOD", "HTTPS protocol is enabled."))
    else:
        findings.append(("BAD", "HTTPS protocol is not enabled."))

    # SSL
    if result["ssl"]["status"] == "Valid":
        findings.append(("GOOD", "SSL certificate is valid."))
    else:
        findings.append(("BAD", "SSL certificate is invalid."))

    # DNS
    if result["checks"]["dns_status"] == "Valid":
        findings.append(("GOOD", "DNS records resolved successfully."))
    else:
        findings.append(("BAD", "DNS resolution failed."))

    # Domain Age
    age = result["checks"]["domain_age"]

    if age >= 35:
        findings.append(("GOOD", f"Domain age: {age} days"))

    elif age >= 90:
        findings.append(("WARNING", f"Domain is relatively new ({age} days)"))

    else:
        findings.append(("BAD", f"Very new domain ({age} days)"))

    # VirusTotal
    if result["virustotal"]["malicious"] == 0 and result["virustotal"]["suspicious"] == 0:
        findings.append(("GOOD", "No malicious detections in VirusTotal."))

    elif result["virustotal"]["malicious"] == 0:
        findings.append(("WARNING", "Suspicious detections found."))

    else:
        findings.append(("BAD", "Malicious detections found."))

    
    rows = []

    for status, message in findings:

        if status == "GOOD":
            color = GREEN
            icon = "✔"

        elif status == "WARNING":
            color = ORANGE
            icon = "⚠"

        else:
            color = RED
            icon = "✖"

        rows.append([
            Paragraph(
                f"<font color='{color}'><b>{icon} {message}</b></font>",
                BODY_STYLE
            )
        ])

    
    table = Table(rows, colWidths=[6.7*inch])

    table.setStyle(TableStyle([
        ("BACKGROUND",(0,0),(-1,-1),WHITE),

        ("TOPPADDING",(0,0),(-1,-1),4),
        
        ("BOTTOMPADDING",(0,0),(-1,-1),4),

        ("BOX",(0,0),(-1,-1),0.5,colors.HexColor("#D1D5DB")),

        ("TOPPADDING",(0,0),(-1,-1),4),

        ("LEFTPADDING",(0,0),(-1,-1),4),

    ]))

    return table

# -----------------------------
# SECURITY RECOMMENDATIONS
# -----------------------------

def build_security_recommendations(result):

    risk = result["result"]["risk"]

    recommendations = []

    if risk == "SAFE":
        color = GREEN

        icon = "✔"

        recommendations = [
            "Always verify the domain before entering credentials.",
            "Continue using HTTPS websites.",
            "Keep browsers and antivirus updated.",
            "Use VirusTotal for unknown links.",
            "Remain cautious of unexpected emails."
        ]

    elif risk == "SUSPICIOUS":
        color = ORANGE

        icon = "⚠"

        recommendations = [
            "Verify the sender before opening the website.",
            "Avoid entering passwords until verified.",
            "Inspect the SSL certificate carefully.",
            "Cross-check the URL using VirusTotal.",
            "Report suspicious URLs if necessary."
        ]

    else:
        color = RED

        icon = "✖"

        recommendations = [
            "Do NOT open this website.",
            "Never enter passwords or OTPs.",
            "Report this URL immediately.",
            "Block the domain if used inside an organization.",
            "Delete emails containing this URL."
        ]

    rows = []

    for item in recommendations:

        rows.append([
            Paragraph(
                f"<font color='{color}'><b>{icon} {item}</b></font>",
                BODY_STYLE
            )
        ])

    table = Table(rows, colWidths=[6.7*inch])

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,-1),WHITE),

        ("BOX",(0,0),(-1,-1),0.5,colors.HexColor("#D1D5DB")),

        ("RIGHTPADDING",(0,0),(-1,-1),8),

        ("BOTTOMPADDING",(0,0),(-1,-1),6),

        ("TOPPADDING",(0,0),(-1,-1),6),

        ("LEFTPADDING",(0,0),(-1,-1),8),

    ]))

    return [
        Paragraph("<b>6. SECURITY RECOMMENDATIONS</b>", SECTION_STYLE),
        Spacer(1,8),
        table
    ]

# -----------------------------
# JSON Export
# -----------------------------
def export_json(result, filename="report.json"):
    with open(filename, "w") as file:
        json.dump(result, file, indent=4)

    return filename


# -----------------------------
# Helper Function
# -----------------------------
def make_table(data, header_color):

    table = Table(data, colWidths=[2.2 * inch, 3.6 * inch])

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#EAF4FF")),

        ("GRID", (0, 0), (-1, -1), 1, colors.grey),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),

        ("VALIGN", (0, 0), (-1, -1), "MIDDLE")

    ]))

    return table

def generate_report_id():
    return "PHISH-" + datetime.now().strftime("%Y%m%d-%H%M%S")


# -----------------------------
# PDF Export
# -----------------------------
def export_pdf(result, filename="report.pdf"):

    doc = SimpleDocTemplate(
        filename,
        leftMargin=0.4*inch,
        rightMargin=0.4*inch,
        topMargin=0.45*inch,
        bottomMargin=0.45*inch
    )

    styles = getSampleStyleSheet()

    story = []

    story.extend(build_header(result))
    story.extend(build_risk_summary(result)) 
    story.extend(build_dashboard(result))
    story.extend(build_security_recommendations(result))

    divider = Table(
        [[""]],
        colWidths=[6.8*inch]
    )

    divider.setStyle(TableStyle([
        ("LINEBELOW", (0,0), (-1,-1), 1.2, NAVY),

        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
    ]))

    story.append(divider)
    
    # ---------------------------
    # Footer
    # ---------------------------

    story.append(Spacer(1,20))

    story.append(
        Paragraph(
            "<para align='center'><font color='#666666'>© 2026 PhishGuard. All rights reserved.</font></para>",
            styles["BodyText"]
        )
    )

    doc.build(story)

    return filename